uv run python drifting.py \
    --dataset imagenet \
    --data-root ./data/imagenette2-160 \
    --output-dir ./outputs/drifting_imagenette_dit \
    --generator-arch dit \
    --image-size 128 \
    --batch-size 32 \
    --latent-dim 512 \
    --dit-patch-size 8 \
    --dit-hidden-dim 1024 \
    --dit-depth 16 \
    --dit-heads 16 \
    --dit-mlp-ratio 4.0 \
    --cond-drop-prob 0.1 \
    --lr 2e-4 \
    --weight-decay 0.01 \
    --class-conditioning \
    --feature-backbone resnet18 \
    --temperatures 0.02 0.05 0.2 \
    --epochs 50 \
    --log-every 50 \
    --sample-every 100 \
    --sample-count 40 \
    --sample-nrow 10 \
    --checkpoint-every 2000
