uv run python drifting.py \
    --dataset imagenet \
    --data-root ./data/imagenette2-160 \
    --output-dir ./outputs/drifting_imagenette64_core \
    --image-size 64 \
    --batch-size 32 \
    --latent-dim 256 \
    --base-channels 96 \
    --lr 2e-4 \
    --weight-decay 0.01 \
    --class-conditioning \
    --feature-backbone resnet18 \
    --temperatures 0.02 0.05 0.2 \
    --epochs 50 \
    --log-every 50 \
    --sample-every 100 \
    --sample-count 40 \
    --sample-nrow 10 \
    --checkpoint-every 2000
